# Generated by Django 2.1 on 2020-05-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administratror',
            new_name='Administrator',
        ),
    ]
